#!/bin/zsh

# find and fetch 1 wallpaper
bb=$(find /home/zhy7ne/Projects/dotFILES/wallpapers/ -type f -name "*.jpg" | shuf -n 1)

# set fetched wallpaper
xwallpaper --zoom $bb

# pywal clear cache and set colorscheme
wal -c
wal -n -q -i $bb

# convert wallpaper into bg file
cp $bb /home/zhy7ne/.zuckless-bg.jpg

# apply colorscheme to bar
xdotool key super+F5
