# Window decorations will be removed when tiling if set to true
remove_decorations = false

# Zentile will ignore windows added to this list.
# You'll have to add WM_CLASS property of the window you want ignored.
# You can get WM_CLASS property of a window, by running "xprop WM_CLASS" and clicking on the window.
# ignore = ['ulauncher', 'gnome-screenshot']

# Adds spacing between windows
gap = 10

# How much to increment the master area size.
proportion = 0.2

[keybindings]
# key sequences can have zero or more modifiers and exactly one key.
# example: Control-Shift-t has two modifiers and one key.
# You can view which keys activate which modifier using the 'xmodmap' program.
# Key symbols can be found by pressing keys using the 'xev' program

# Tile the current workspace.
tile = "Control-Super-y"

# Untile the current workspace.
untile = "Control-Super-u"

# Make the active window as master.
make_active_window_master = "Control-Super-m"

# Increase the number of masters.
increase_master = "Control-Super-i"

# Decrease the number of masters.
decrease_master = "Control-Super-o"

# Cycles through the available layouts.
switch_layout = "Control-Super-l"

# Moves focus to the next window.
next_window = "Control-Super-n"

# Moves focus to the previous window.
previous_window = "Control-Super-p"

# Increases the size of the master windows.
increment_master = "Control-Super-bracketright"

# Decreases the size of the master windows.
decrement_master = "Control-Super-bracketleft"
