#!/bin/sh

# runs when log unto dwm

# runs xuckless
#/home/zhy7ne/.xuckless &
/home/zhy7ne/.xuckless-default &

# copies log background as hidden in home direcory for reset background
#cp /usr/share/wallpapers/bb.jpg /home/zhy7ne/.xuckless-bg.jpg &

# run picom compositor in bg
picom &

# run slstatus bar in bg
slstatus &

# apply colorscheme to bar
xdotool key super+F5 &

# disable screendim
xset dpms 0 0 0
xset s off

#cpu(){
#    read cpu a b c previdle rest < /proc/stat
#    prevtotal = $((a+b+c+previdle))
#    sleep 0.5
#    read cpu a b c idle rest < /proc/stat
#    total = $((a+b+c+idle))
#    cpu = $((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
#    if [ $cpu -gt 9 ];then
#        echo " $cpu% cpu"
#    elif [ $cpu -gt 99 ];then
#        echo "$cpu% cpu"
#    else
#        echo "  $cpu% cpu"
#    fi
#}

#dt(){
#    dt = "$(date "+ %A, %B %d - %H:%M")"
#    echo "$dt"
#}

#while true; do
#    xsetroot -name "| $(cpu) | $(dt)"
#    sleep 1s
#done &

#xsetroot -name " |zhy7ne"

# run dwm
dwm 
