#!/bin/sh

# runs when log unto dwm

# runs xuckless
#/home/zhy7ne/.scripts/.xuckless &
/home/zhy7ne/.scripts/.xuckless-default &

# copies log background as hidden in home direcory for reset background
#cp /usr/share/wallpapers/bb.jpg /home/zhy7ne/.xuckless-bg.jpg &

# run lxpolkit to manage authorizations on dwm
lxpolkit &

# run picom compositor in bg
picom &

# run slstatus bar in bg
slstatus &

# apply colorscheme to bar
xdotool key super+F5 &

# disable screendim
xset dpms 0 0 0
xset s off

# run dwm
dwm
